### ISSUE TITLE
Incorrect exception thrown if failed to auto resolve nested dependency

### ISSUE THREAD

**Issue by Luc45** [lucatume/di52#12]
Hi Luca,

This is an old issue I've always faced with DI52.

Consider the following scenario:

```php
class Car {
	public function __construct( Engine $e ) {}
}

class Engine {
	public function __construct( NonExisting $g ) {}
}

$container = new tad_DI52_Container();
$container->make( Car::class );
```

`( ! ) Fatal error: Uncaught RuntimeException: Error while making 'Car': 'Car' is not a bound alias or an existing class. in /shared/httpd/di52/htdocs/di52/src/tad/DI52/Container.php on line 352`

The exception tells me that `Car` doesn't exist, where actually the problem is in my `Engine` because it depends on `NonExisting`.

An explicit binding throws an accurate error:

```php
$container = new tad_DI52_Container();

$container->bind( Car::class, function ( tad_DI52_Container $c ) {
	return new Car( $c->make( NonExisting::class ) );
	// or return new Car( new NonExisting );
} );

$container->make( Car::class );
```

`( ! ) Fatal error: Uncaught RuntimeException: Error while making 'NonExisting': Class NonExisting does not exist in /shared/httpd/di52/htdocs/di52/src/tad/DI52/Container.php on line 352`

I might come up with a PR for it, but I felt like sharing this here first to give you a head start in case you want to look into this yourself.

**Comment by Luc45** [comment]
Fix: https://github.com/lucatume/di52/pull/14

Before: `( ! ) Fatal error: Uncaught RuntimeException: Error while making 'Car': 'Car' is not a bound alias or an existing class. in /shared/httpd/di52/htdocs/di52/src/tad/DI52/Container.php on line 352`

After: `( ! ) Fatal error: Uncaught RuntimeException: 'Car' => Error while making 'Engine': Class NonExisting does not exist in /shared/httpd/di52/htdocs/di52/src/tad/DI52/Container.php on line 360`

Please read the notes in the PR

**Comment by lucatume** [comment]
@Luc45 yep, old and annoying issue, thanks for tackling it.
