### ISSUE TITLE
Request for feedback: Define Singleton or Bind as default auto-resolve behavior when creating a new Container instance

### ISSUE THREAD

**Issue by Luc45** [lucatume/di52#13]
When the container auto injects a dependency, it returns a new instance of the dependency by default. (bind behavior)

Most of the cases, however, I'd like to inject the same instance (singleton behavior).

I'd like to propose a feature, which is to define the default behavior for auto resolving when creating an instance of the Container:

```
class tad_DI52_Container {
    public function __construct( $autoResolveAsSingleton = false ) {
        $this->autoResolveAsSingleton = $autoResolveAsSingleton;
    }
}

$container = new tad_DI52_Container( true );
```

Before I jump into trying to come a PR for this, I'd like to ask for feedback on this idea.

Thanks.

**Comment by lucatume** [comment]
Let me see if I'm reading this right:

```php
class A{}

class S{}

interface CInterface{}

class C implements CInterface{}

class B{
  public $a;
  public $s;
  public $c;
  public $d;

  public function __construct(A $a, S $s, CInterface $c, D $d){
    $this->a = $a;
    $this->s = $s;
    $this->c = $c;
    $this->d = $d;
  }
}

$container1 = new new tad_DI52_Container();
$container1->singleton(S::class);
$container1->bind(CInterface::class, C::class);
$container1->bind(D::class, D::class);

$b1 = $container1->make(B::class);
$b2 = $container1->make(B::class);

assert($b1->a !== $b2->a);
assert($b1->s === $b2->s);
assert($b1->c !== $b2->c);
assert($b1->d !== $b2->d);

$container2 = new new tad_DI52_Container(true);
$container2->singleton(S::class);
$container2->bind(CInterface::class, C::class);
$container2->bind(D::class, D::class);

$b3 = $container2->make(B::class);
$b4 = $container2->make(B::class);

assert($b3->a === $b4->a);
assert($b3->s === $b4->s);

// What should this be?
assert($b3->c === $b4->c);

// What should this be?
assert($b3->d === $b4->d);
```

What worries me is how the general behavior implemented by the container, changed by the resolve dependency flag, might contradict, or make it more difficult reading the implementation binding code.
I think some check should be applied to make sure that the default behavior should be applied where not specified by a `bind` or `singleton` call.
The check, then, should be made at `make` time, not at `bind` or `singleton` time and the performance hit worries me a bit.

I do not think the idea is a bad one, it would just require some care and test coverage for a number of edge cases that might not be that obvious.

**Comment by Luc45** [comment]
> // What should this be?
> assert($b3->c === $b4->c);
> 
> // What should this be?
> assert($b3->d === $b4->d);

False, as they are explicitly defined as `bind`.

**Comment by Luc45** [comment]
The general goal of this idea is to reduce Service Providers like this:

```php
class Car_Service_Provider extends tad_DI52_ServiceProvider {
    
    /** @var tad_DI52_ContainerInterface */
    protected $container;
    
    public function register()
    {
        $this->container->singleton(Car::class, Car::class);
        $this->container->singleton(Engine::class, Engine::class);
        $this->container->singleton(UpperEngine::class, UpperEngine::class);
        $this->container->singleton(CombustionChamber::class, CombustionChamber::class);
        $this->container->bind(Valve::class, Valve::class);
        $this->container->singleton(LowerEngine::class, LowerEngine::class);
        $this->container->singleton(DriveShaft::class, DriveShaft::class);
        $this->container->singleton(Clutch::class, Clutch::class);
    }
}
```

To this:

```php
<?php

class Car_Service_Provider extends tad_DI52_ServiceProvider {
    
    /** @var tad_DI52_ContainerInterface */
    protected $container;
    
    public function register()
    {
        $this->container->bind(Valve::class, Valve::class);
    }
}
```

I want a `singleton` instead of a `bind` most of the times.

Now the question is, using `singleton` is more memory and CPU friendly, but also ties the application in a global state.

In your code, do you find yourself using more `bind` or `singleton`? Do you think using `singleton` should be the rule or the exception?

I ask this because if it doesn't make sense, from an architectural point of view, to use more singletons than binds, then we don't even need to discuss the implementation details of this feature if it doesn't make sense in the first place.

Looking forward for your thoughts.
Lucas

**Comment by lucatume** [comment]
While singletons make sense for a lot of higher-level code, their "assumption" makes them dangerous tools, in my experience.

I do not see a real advantage in going from this:

```php
$this->container->singleton(Valve::class, Valve::class);
```

to this:

```php
$this->container->bind(Valve::class, Valve::class);
```

I use one container instance for a whole application, I can see the advantage in one part of the code, but it might not apply to all my code.

What API would allow, then, to bind an implementation **not** as a singleton in a container instance created with `$container = new tad_DI52_Container(true);`? I cannot think of one that is not clunky.

Your second example, then, creates a tree problem that can create undesired side-effects when the type of binding is inferred:

```php
class A{}

class B {
    public function __construct(A $a){}
}

class C {
    public function __construct(A $a){}
}

$container = new new tad_DI52_Container();

// Since A is a dependency of B, then A will be bound as a singleton?
$container->singleton(B::class, B::class);

// Will A be re-bound as non-singleton? Will it stay the same?
$container->bind(C::class, C::class);
```

Furthermore, this code requires early discovery and resolution of the dependency tree imposing an upfront cost to the simple registration, before any usage.

I do not think this would be an improvement.

**Comment by Luc45** [comment]
@lucatume Either you or me are wrong. I think you are missing the point.

```php
// Will A be re-bound as non-singleton? Will it stay the same?
$container->bind(C::class, C::class);
```

`A::class` is not re-bound as non-singleton, `C::class` is.

When requested, a new instance of `C::class` will be returned, with the dependency `A::class` being always the same instance in all of `C::class` instances.

**Comment by lucatume** [comment]
You're correct, I had not considered the issue enough, part of my argument is moot, thanks for clarifying.

> What API would allow, then, to bind an implementation not as a singleton in a container instance created with $container = new tad_DI52_Container(true);? I cannot think of one that is not clunky.

This question stands, though.

Example:

```php
class A{}

class B {
    public function __construct(A $a){}
}

class C {
    public function __construct(A $a){}
}

// Singleton all the things.
$container = new new tad_DI52_Container(true);

// B will be bound as singleton, the use of the `singleton` method is just reinforcing it.
$container->singleton(B::class, B::class);

// C will be bound as singleton, since that is the mode of the container instance.
$container->bind(C::class, C::class);

// How to bind A as a non-singleton?
$container->something(A::class);
```

**Comment by Luc45** [comment]
```php
// C will be bound as singleton, since that is the mode of the container instance.
$container->bind(C::class, C::class);
```

No, if you explicitly define it as a bind, `C::class` will be a bind.

Similarly, today, the container resolves everything as a `bind`, but you can override it with `$container->singleton(C::class)`.

This feature proposal just inverts this logic, making the container resolve everything as `singleton` by default, but you can override it by setting `$container->bind(C::class)`.

Once you understand my proposal and still think it's a bad idea, I'll happily close this.

**Comment by lucatume** [comment]
As long as the default behavior does not change, not to bind as singleton, this seems like a fine idea.
What do you need to move ahead with this?

**Comment by lucatume** [comment]
I'm addressing this in #26
