### ISSUE TITLE
Upgrade PHP version

### ISSUE THREAD

**Issue by Luc45** [lucatume/di52#24]
## Introduction
Looking at the [Dependency Graph](https://github.com/lucatume/di52/network/dependents?package_id=UGFja2FnZS01NDI4OTg2MDk%3D) _(which excludes private packages, but it's a somewhat reliable source of information)_, DI52 is mostly used in the WordPress environment.

PHP 5.2 [is used](https://wordpress.org/about/stats/#php_versions) in 0.8% of WordPress websites today. Outside the WordPress environment that's pretty much [consistent](https://blog.packagist.com/php-versions-stats-2020-1-edition/).

Having PHP 5.2 compatibility made a lot of sense when DI52 was released, because that was the minimum PHP version for WordPress. Since April 2019, with the release of WordPress 5.1, the minimum PHP version was raised to 5.6.

## Why am I opening this now?

DI52 adds an annoying and no longer maintained dependency to a project, which is [xrstf/composer-php52](https://github.com/composer-php52/composer-php52). This is not a development dependency, this is a REAL dependency that's added on all projects that depend on DI52.

I, as a developer of [WP STAGING](https://github.com/WP-Staging/wp-staging), want to use DI52, but I don't want to depend on `xrstf/composer-php52` because our minimum PHP version is 5.6.

## What to do about it

1. I can fork it and create a `Luc45/DI56`, for which I would ask your blessing to do so. 
2. You create a `lucatume/DI56` repository which is an exact copy of `DI52` but with `composer5-3.json` as default, and I will happily contribute to it.
3. We move `xrstf/composer-php52` to `suggest` in `composer.json`, add a `php-52-compatibility.md` file in the project, explaining that for PHP 5.2 compatibility the person should add the `scripts` portion in his `composer.json` and install it with `composer update --install-suggests`.

**Comment by lucatume** [comment]
4. Create version `3.0.0` and rely on semantic versioning to signal it's a breaking change.

This is the path I would take; it's not as simple as removing the dependencies as the package would require pruning to remove any PHP 5.2 related dependency to move its minimum version to 5.6. Documentation would require updates and so on.
Not a momentous task, but one that would require some work.
I would keep the PHP 5.2 class names aliased to new and namespaced class names to avoid breaking back-compatibility, in regards to class names, without a real benefit since there are so few classes. 

Edit: I've corrected the version to `3.0.0`.

**Comment by Luc45** [comment]
OK. I'll get started with this, open a PR, and please feel free to commit to it as you see fit.

**Comment by lucatume** [comment]
If you're not in a rush, I would prefer setting the initial setup, I have some backlog to go with that and would like to start on the right foot. Probably in a couple of days.

**Comment by Luc45** [comment]
Of course, thanks for looking into it. :1st_place_medal:

**Comment by Luc45** [comment]
`xrstf/composer-php52` breaks compatibility with prefixers such as [Mozart](https://github.com/coenjacobs/mozart).

I'll temporarily fork DI52 while you work on the upgrade, to get rid of `xrstf/composer-php52` because I need Mozart right now, as WP STAGING is conflicting with The Events Calendar.

> Fatal error: Uncaught ArgumentCountError: Too few arguments to function tad_DI52_Container::singleton(), 1 passed in /homepages/0/d745611666/htdocs/clickandbuilds/YoungPeoplesCounsellingService/ypcs-test/wp-content/plugins/wp-staging-pro/Pro/Template/TemplateServiceProvider.php on line 12 and at least 2 expected in /homepages/0/d745611666/htdocs/clickandbuilds/YoungPeoplesCounsellingService/ypcs-test/wp-content/plugins/the-events-calendar/common/vendor/lucatume/di52/src/tad/DI52/Container.php:732 Stack trace: #0 /homepages/0/d745611666/htdocs/clickandbuilds/YoungPeoplesCounsellingService/ypcs-test/wp-content/plugins/wp-staging-pro/Pro/Template/TemplateServiceProvider.php(12): tad_DI52_Container->singleton('WPStaging\\Frame...') #1 /homepages/0/d745611666/htdocs/clickandbuilds/YoungPeoplesCounsellingService/ypcs-test/wp-content/plugins/wp-staging-pro/Framework/DI/ServiceProvider.php(9): WPStaging\Pro\Template\TemplateServiceProvider->registerClasses() #2 /homepages/0/d745611666/htdocs/clickandbuilds/YoungPeoplesCounselling in /homepages/0/d745611666/htdocs/clickandbuilds/YoungPeoplesCounsellingService/ypcs-test/wp-content/plugins/the-events-calendar/common/vendor/lucatume/di52/src/tad/DI52/Container.php on line 732

_PS: This in no way intends to rush the work. It's just for informational purposes._

**Edit:**

Nope, this is a Mozart bug that can't handle an autoloader path when it's an array https://github.com/lucatume/di52/blob/master/composer.json#L13-L15

It expects `"tad_DI52_": "src/"` instead, but the array is a valid syntax.

**Comment by lucatume** [comment]
You're lighting a fire under me... I will get to this next.
More time, I need more time!

**Comment by Luc45** [comment]
Not my intention, and I was wrong to begin with. It's a Mozart bug.

**Comment by Luc45** [comment]
> `xrstf/composer-php52` breaks compatibility with prefixers such as [Mozart](https://github.com/coenjacobs/mozart).
> 
> I'll temporarily fork DI52 while you work on the upgrade, to get rid of `xrstf/composer-php52` because I need Mozart right now, as WP STAGING is conflicting with The Events Calendar.
> 
> > Fatal error: Uncaught ArgumentCountError: Too few arguments to function tad_DI52_Container::singleton(), 1 passed in /homepages/0/d745611666/htdocs/clickandbuilds/YoungPeoplesCounsellingService/ypcs-test/wp-content/plugins/wp-staging-pro/Pro/Template/TemplateServiceProvider.php on line 12 and at least 2 expected in /homepages/0/d745611666/htdocs/clickandbuilds/YoungPeoplesCounsellingService/ypcs-test/wp-content/plugins/the-events-calendar/common/vendor/lucatume/di52/src/tad/DI52/Container.php:732 Stack trace: #0 /homepages/0/d745611666/htdocs/clickandbuilds/YoungPeoplesCounsellingService/ypcs-test/wp-content/plugins/wp-staging-pro/Pro/Template/TemplateServiceProvider.php(12): tad_DI52_Container->singleton('WPStaging\Frame...') #1 /homepages/0/d745611666/htdocs/clickandbuilds/YoungPeoplesCounsellingService/ypcs-test/wp-content/plugins/wp-staging-pro/Framework/DI/ServiceProvider.php(9): WPStaging\Pro\Template\TemplateServiceProvider->registerClasses() #2 /homepages/0/d745611666/htdocs/clickandbuilds/YoungPeoplesCounselling in /homepages/0/d745611666/htdocs/clickandbuilds/YoungPeoplesCounsellingService/ypcs-test/wp-content/plugins/the-events-calendar/common/vendor/lucatume/di52/src/tad/DI52/Container.php on line 732
> 
> _PS: This in no way intends to rush the work. It's just for informational purposes._
> 
> **Edit:**
> 
> Nope, this is a Mozart bug that can't handle an autoloader path when it's an array https://github.com/lucatume/di52/blob/master/composer.json#L13-L15
> 
> It expects `"tad_DI52_": "src/"` instead, but the array is a valid syntax.

I was in a hurry when I wrote this, sorry if it felt like pressuring you.

To be clear: I have no need for an update to DI52 in the foreseeable future, and if I did, I would hack my way into it myself.

The compatibility between WP STAGING and TEC, first of all, affects only WP STAGING. TEC registers their autoloader first, so you win the [race](https://en.wikipedia.org/wiki/Race_condition#:~:text=A%20race%20condition%20or%20race,the%20possible%20behaviors%20is%20undesirable.).

This bug also affected only one customer so far, as it was a Release Candidate version of WP STAGING.

And lastly, this has nothing to do with DI52. I will prefix WP STAGING dependencies using [PHP-Scoper](https://github.com/humbug/php-scoper). I suggest you add it to your roadmap to do the same, to avoid something like this happening to you in the future.

PS: I have investigated deeply [Mozart](https://github.com/coenjacobs/mozart), [Imposter](https://github.com/TypistTech/imposter-plugin) and [PHP-Scoper](https://github.com/humbug/php-scoper). I could share some insights on their differences if you'd like.

**Comment by lucatume** [comment]
> I was in a hurry when I wrote this, sorry if it felt like pressuring you.
> 
> To be clear: I have no need for an update to DI52 in the foreseeable future, and if I did, I would hack my way into it myself.

Ah, no worries at all. I just wanted to post an update.
Now wp-browser `3.0` has shipped, this will get some love.

I will remove 5.2 dependencies completely, so this should be taken care of.

> PS: I have investigated deeply [Mozart](https://github.com/coenjacobs/mozart), [Imposter](https://github.com/TypistTech/imposter-plugin) and [PHP-Scoper](https://github.com/humbug/php-scoper). I could share some insights on their differences if you'd like.

Please do!

**Comment by lucatume** [comment]
Addressing this in #26
