### ISSUE TITLE
PHP 8.4 deprecation message - nullable types

### ISSUE THREAD

**Issue by Luc45** [lucatume/di52#65]
> Deprecated: _HumbugBoxdb28ee67b803\lucatume\DI52\Builders\ReinitializableBuilderInterface::reinit(): Implicitly marking parameter $afterBuildMethods as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/gregbell/.composer/vendor/woocommerce/qit-cli/qit/vendor/lucatume/di52/src/Builders/ReinitializableBuilderInterface.php on line 7

[Example line](https://github.com/lucatume/di52/blob/master/src/Builders/ReinitializableBuilderInterface.php#L25) where that deprecation is triggered.

I think it's just a matter of making the parameter nullable, eg:

```php
public function reinit(?array $afterBuildMethods = null, ...$buildArgs);
```
It seems nullable types was [introduced](https://www.php.net/manual/en/migration71.new-features.php) in PHP 7.1, though, which would warrant a minimum version bump.

What do you think?

**Comment by lucatume** [comment]
I will try to update to min 7.1 and add 8.4 tests and see where I land.

**Comment by lucatume** [comment]
I've fixed the issues in version 4.0.0 and bumped the minimum version to 7.1.
Thank you again @Luc45 for reporting the issue.

**Comment by Luc45** [comment]
Thank you!

**Comment by Luc45** [comment]
@lucatume Thank you!
